[package]
name = "heros_spirit_utils"
description = "data conversion tools for files used by Hero's Spirit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
zip = { version = "0.6", default_features = false, features = ["deflate", "aes-crypto"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
image = "0.24"
num_enum = "0.5"
enum-utils = "0.1"
