name: build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ""

      - name: Build
        run: cargo build --release --all-features

      - name: Archive Linux Artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: heros_spirit_utils_linux
          path: ./target/release/heros_spirit_utils
          if-no-files-found: error

      - name: Archive Windows Artifacts
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: heros_spirit_utils_windows
          path: ./target/release/heros_spirit_utils.exe
          if-no-files-found: error
